# Generated by Django 5.2.dev20240712180928 on 2024-08-19 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('MOT', 'Motors'), ('FAS', 'Fashion'), ('ELE', 'Electronics'), ('ART', 'Collectibles&Art'), ('HGA', 'Home&Garden'), ('SPO', 'Sport'), ('TOY', 'Toys'), ('BUS', 'Business&Industrial'), ('MUS', 'Music')], max_length=3),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 19, 21, 27, 40, 233877, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 21, 21, 27, 40, 233877, tzinfo=datetime.timezone.utc)),
        ),
    ]
