# Generated by Django 5.2.dev20240712180928 on 2024-08-02 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 20, 11, 37, 823137, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
