# Generated by Django 5.2.dev20240712180928 on 2024-08-02 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlistings_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 20, 22, 17, 67646, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 20, 22, 17, 67646, tzinfo=datetime.timezone.utc)),
        ),
    ]
