# Generated by Django 5.2.dev20240712180928 on 2024-08-02 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlistings_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 21, 33, 56, 564214, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 21, 33, 56, 564214, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='image_url',
            field=models.URLField(blank=True, max_length=900, null=True),
        ),
    ]
