# Generated by Django 5.2.dev20240712180928 on 2024-08-07 17:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlistings_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 17, 10, 41, 314100, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 17, 10, 41, 314100, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_listing', to='auctions.auctionlistings')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
