# Generated by Django 5.2.dev20240712180928 on 2024-08-07 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionlistings_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 17, 22, 27, 79246, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 17, 22, 27, 79246, tzinfo=datetime.timezone.utc)),
        ),
    ]
