# Generated by Django 5.2.dev20240712180928 on 2024-11-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Surname',
        ),
    ]
