# Generated by Django 5.2.dev20240712180928 on 2024-11-18 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_group_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='contacts',
            field=models.ManyToManyField(to='contacts.contact'),
        ),
    ]
