# Generated by Django 5.2.dev20240712180928 on 2024-12-05 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_alter_contact_nickname_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.group'),
        ),
    ]
