# Generated by Django 5.2.dev20240712180928 on 2024-09-20 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='users_followed',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='users_following',
        ),
    ]
